version: '3.8'

services:
  db:
    image: postgres:14
    container_name: docker_potter_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: potterdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - potter_net

  api:
    build: ./docker_potter_api
    container_name: docker_potter_api
    image: w3sll3ym/docker_potter_api
    environment:
      DATABASE_URL: postgres://user:password@db:5432/potterdb
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - potter_net

  web:
    build: ./docker_potter_web
    container_name: docker_potter_web
    image: w3sll3ym/docker_potter_web
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - potter_net

volumes:
  postgres_data:

networks:
  potter_net:
    driver: bridge